# fly.toml app configuration file generated for backenvillagolbackend on 2025-08-17T02:35:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backenvillagolbackend'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  MONGO_URI=mongodb+srv://villagolvn:10263104@villagolbd.0aispxh.mongodb.net/?retryWrites=true&w=majority&appName=VillaGolBD
  PORT=5000
  JWT_SECRET=your_jwt_secret

